### ISSUE TITLE
Unable to run gradle example in Intellij

### ISSUE THREAD

**Issue by dzwicker** [wildfly-swarm/wildfly-swarm-examples#34]
Hi,

great work ;-)

I'm playing with the gradle example and using the terminal and the swarm-plugin everthing works well. But importing the project with idea and starting the main from within idea there are libs missing. THe same happens if i user the `installApp` task from gradle.

```
org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/common-beans/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:32)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:50)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
	at org.jboss.modules.Module.addPaths(Module.java:1071)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.wildfly.swarm.container.Container.createServer(Container.java:138)
	at org.wildfly.swarm.container.Container.<init>(Container.java:108)
	at org.wildfly.swarm.container.Container.<init>(Container.java:96)
	at org.wildfly.swarm.examples.gradle.Main.main(Main.java:15)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.common:jboss-common-beans:2.0.0.Final' (position: END_TAG seen ...<artifact name="org.jboss.common:jboss-common-beans:2.0.0.Final"/>... @31:75) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 14 more
org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xalan/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:32)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:50)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.getPaths(Module.java:1359)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.container.runtime.RuntimeServer.<init>(RuntimeServer.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.wildfly.swarm.container.Container.createServer(Container.java:141)
	at org.wildfly.swarm.container.Container.<init>(Container.java:108)
	at org.wildfly.swarm.container.Container.<init>(Container.java:96)
	at org.wildfly.swarm.examples.gradle.Main.main(Main.java:15)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'xalan:serializer:2.7.1.jbossorg-2' (position: END_TAG seen ...rces>\n        <artifact name="xalan:serializer:2.7.1.jbossorg-2"/>... @28:61) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 25 more
org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xerces/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:32)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:50)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.getPaths(Module.java:1359)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.container.runtime.RuntimeServer.<init>(RuntimeServer.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.wildfly.swarm.container.Container.createServer(Container.java:141)
	at org.wildfly.swarm.container.Container.<init>(Container.java:108)
	at org.wildfly.swarm.container.Container.<init>(Container.java:96)
	at org.wildfly.swarm.examples.gradle.Main.main(Main.java:15)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'xerces:xercesImpl:2.11.0.SP4' (position: END_TAG seen ...resources>\n        <artifact name="xerces:xercesImpl:2.11.0.SP4"/>... @28:56) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 25 more
org.jboss.modules.ModuleLoadError: Error loading module from modules/org/apache/xerces/main/module.xml
	at org.jboss.modules.ModuleLoadException.toError(ModuleLoadException.java:74)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1384)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.container.runtime.RuntimeServer.<init>(RuntimeServer.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.wildfly.swarm.container.Container.createServer(Container.java:141)
	at org.wildfly.swarm.container.Container.<init>(Container.java:108)
	at org.wildfly.swarm.container.Container.<init>(Container.java:96)
	at org.wildfly.swarm.examples.gradle.Main.main(Main.java:15)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'xerces:xercesImpl:2.11.0.SP4' (position: END_TAG seen ...resources>\n        <artifact name="xerces:xercesImpl:2.11.0.SP4"/>... @28:56) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:32)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:50)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.getPaths(Module.java:1359)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
	... 16 more
```

**Comment by emag** [comment]
How did you import gradle example project?
Since wildfly-swarm-examples contain maven and gradle project, so maybe you need to open gradle example as other `gradle` project, not wildfly-swarm-example-parent(its maven project).

![screenshot from 2015-11-10 02-47-40](https://cloud.githubusercontent.com/assets/1188893/11041497/85e2e2f0-8755-11e5-8654-aa7ddb5758b1.png)

**Comment by dzwicker** [comment]
I have imported the 'gradle' project as the root. Same as in your screenshot. I changed the version for the wildfly-swarm-XXX to 1.0.0.Alpha5. I'll post the dependencies resolved by gradle. Can you check in your project? On dep missing is the `xerces:xercesImpl:2.11.0.SP4` can you figure out where you idea resolve this?

![screen shot 2015-11-09 at 19 25 59](https://cloud.githubusercontent.com/assets/500483/11042503/cd3e542e-8717-11e5-87f8-f8473dc54505.png)

**Comment by helio-frota** [comment]
here is working fine too..
are you did sometime a install from wildfly swarm itself ?
i mean, clone wildfly-swarm and then mvn clean install ?
if not, i can drop all dependencies here and try to use only the example to double check.

intellij console output:
```
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/home/hf/dev/idea-IC-143.381.42/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.fc22.x86_64/jre/lib/rt.jar:/home/hf/dev/jboss/wildfly-swarm-examples/gradle/build/classes/main:/home/hf/dev/jboss/wildfly-swarm-examples/gradle/build/resources/main:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-jaxrs/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-jaxrs-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-container/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-container-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-jaxrs-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-jaxrs-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-undertow/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-undertow-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-naming/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-naming-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-security/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-security-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final/jboss-jaxrs-api_2.0_spec-1.0.0.Final.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-bootstrap/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-bootstrap-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-container-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-container-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-api/1.1.2/shrinkwrap-api-1.1.2.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-spi/1.1.2/shrinkwrap-spi-1.1.2.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-impl-base/1.1.2/shrinkwrap-impl-base-1.1.2.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-jboss/2.0.0-alpha-8/shrinkwrap-descriptors-api-jboss-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-jboss/2.0.0-alpha-8/shrinkwrap-descriptors-impl-jboss-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/ow2/asm/asm-all/5.0.4/asm-all-5.0.4.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-undertow-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-undertow-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-naming-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-naming-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-security-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-security-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-logging/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-logging-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-io/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-io-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-ee/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-ee-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/jboss/spec/javax/servlet/jboss-servlet-api_3.1_spec/1.0.0.Final/jboss-servlet-api_3.1_spec-1.0.0.Final.jar:/home/hf/.m2/repository/org/jboss/spec/javax/websocket/jboss-websocket-api_1.1_spec/1.1.1.Final/jboss-websocket-api_1.1_spec-1.1.1.Final.jar:/home/hf/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/home/hf/.m2/repository/org/jboss/spec/javax/sql/jboss-javax-sql-api_7.0_spec/2.0.0.Final/jboss-javax-sql-api_7.0_spec-2.0.0.Final.jar:/home/hf/.m2/repository/org/wildfly/configuration/wildfly-config-api/0.2.5/wildfly-config-api-0.2.5.jar:/home/hf/.m2/repository/org/wildfly/configuration/generator/0.2.5/generator-0.2.5.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-javaee/2.0.0-alpha-8/shrinkwrap-descriptors-api-javaee-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-javaee/2.0.0-alpha-8/shrinkwrap-descriptors-impl-javaee-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-logging-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-logging-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-io-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-io-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/wildfly/swarm/wildfly-swarm-ee-modules/1.0.0.Alpha5-SNAPSHOT/wildfly-swarm-ee-modules-1.0.0.Alpha5-SNAPSHOT.jar:/home/hf/.m2/repository/org/jboss/spec/javax/enterprise/concurrent/jboss-concurrency-api_1.0_spec/1.0.0.Final/jboss-concurrency-api_1.0_spec-1.0.0.Final.jar:/home/hf/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/home/hf/.m2/repository/org/jboss/forge/roaster/roaster-jdt/2.15.0.Final/roaster-jdt-2.15.0.Final.jar:/home/hf/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-base/2.0.0-alpha-8/shrinkwrap-descriptors-api-base-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-base/2.0.0-alpha-8/shrinkwrap-descriptors-impl-base-2.0.0-alpha-8.jar:/home/hf/.m2/repository/org/jboss/forge/roaster/roaster-api/2.15.0.Final/roaster-api-2.15.0.Final.jar:/home/hf/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-spi/2.0.0-alpha-8/shrinkwrap-descriptors-spi-2.0.0-alpha-8.jar:/home/hf/dev/idea-IC-143.381.42/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain org.wildfly.swarm.examples.gradle.Main
tmpDir: /tmp
15:56:15,925 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
15:56:16,032 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 2.0.0.CR1 "Kenny" starting
2015-11-09 15:56:16,403 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 11) WFLYNAM0001: Activating Naming Subsystem
2015-11-09 15:56:16,410 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0003: Undertow 1.3.0.CR1 starting
2015-11-09 15:56:16,410 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 12) WFLYSEC0002: Activating Security Subsystem
2015-11-09 15:56:16,410 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 10) WFLYUT0003: Undertow 1.3.0.CR1 starting
2015-11-09 15:56:16,412 INFO  [org.jboss.as.security] (MSC service thread 1-8) WFLYSEC0001: Current PicketBox version=4.9.3.Final
2015-11-09 15:56:16,417 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 13) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
2015-11-09 15:56:16,423 INFO  [org.jboss.as.naming] (MSC service thread 1-2) WFLYNAM0003: Starting Naming Service
2015-11-09 15:56:16,433 INFO  [org.xnio] (MSC service thread 1-3) XNIO version 3.3.2.Final
2015-11-09 15:56:16,441 INFO  [org.xnio.nio] (MSC service thread 1-3) XNIO NIO Implementation Version 3.3.2.Final
2015-11-09 15:56:16,458 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0012: Started server default-server.
2015-11-09 15:56:16,492 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0006: Undertow HTTP listener default listening on [0:0:0:0:0:0:0:0]:8080
2015-11-09 15:56:16,585 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.0.0.CR1 "Kenny" started in 700ms - Started 68 of 75 services (14 services are lazy, passive or on-demand)
2015-11-09 15:56:18,856 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0027: Starting deployment of "9cb56c8c-d3b1-4fd3-b1e3-4f9d84aa49e6.war" (runtime-name: "9cb56c8c-d3b1-4fd3-b1e3-4f9d84aa49e6.war")
2015-11-09 15:56:20,303 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0018: Host default-host starting
2015-11-09 15:56:20,541 INFO  [org.jboss.resteasy.spi.ResteasyDeployment] (ServerService Thread Pool -- 7) Deploying javax.ws.rs.core.Application: class org.wildfly.swarm.generated.WildFlySwarmDefaultJAXRSApplication
2015-11-09 15:56:20,555 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 7) WFLYUT0021: Registered web context: /
2015-11-09 15:56:20,570 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "9cb56c8c-d3b1-4fd3-b1e3-4f9d84aa49e6.war" (runtime-name : "9cb56c8c-d3b1-4fd3-b1e3-4f9d84aa49e6.war")
```

**Comment by emag** [comment]
@dzwicker Hmm, it works 1.0.0.Alpha5 on my environment.

Please check the following point:

* Are you using JDK 8?
* What platform?(Windows/Linux/OS X)
* Is this reproduce it at latest WildFly Swarm HEAD(Alpha6-SNAPSHOT) and other example projects using `maven`?

**Comment by helio-frota** [comment]
hi @dzwicker 
I dropped the m2 directory and downloaded all again
https://gist.github.com/helio-frota/6eb528734cf6731b65ac#file-wf-swarm-gradle-build

But still getting an error when running from the main class inside intellij...
```
...
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.common:jboss-common-beans:2.0.0.Final' (position: END_TAG seen ...<artifact name
...
```

So, @bobmcwhirter did changes to ensure jboss-common-beans will resolve now at runtime with an empty .m2

**Comment by bobmcwhirter** [comment]
Did those changes I did help?

**Comment by dzwicker** [comment]
@emag I'm running SUN JDK 8 (i can see that the others run openJDK, this should not be a problem) on OS X (10.11).

Using Alpah6 (61fc31d) the stacktrace is another:

```
Exception in thread "main" org.jboss.shrinkwrap.impl.base.ExtensionLoadingException: Failed to instantiate class of type class org.jboss.shrinkwrap.impl.base.MemoryMapArchiveImpl. The underlying constructor threw an exception.
	at org.jboss.shrinkwrap.impl.base.ServiceExtensionLoader.createExtension(ServiceExtensionLoader.java:365)
	at org.jboss.shrinkwrap.impl.base.ServiceExtensionLoader.createFromLoadExtension(ServiceExtensionLoader.java:223)
	at org.jboss.shrinkwrap.impl.base.ServiceExtensionLoader.load(ServiceExtensionLoader.java:108)
	at org.jboss.shrinkwrap.impl.base.ArchiveBase.as(ArchiveBase.java:648)
	at org.jboss.shrinkwrap.api.ArchiveFactory.create(ArchiveFactory.java:150)
	at org.jboss.shrinkwrap.api.ArchiveFactory.create(ArchiveFactory.java:110)
	at org.jboss.shrinkwrap.api.ShrinkWrap.create(ShrinkWrap.java:136)
	at org.wildfly.swarm.examples.gradle.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.jboss.shrinkwrap.impl.base.ServiceExtensionLoader.createExtension(ServiceExtensionLoader.java:354)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/jboss/shrinkwrap/descriptor/spi/node/NodeDescriptorImplBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.shrinkwrap.descriptor.api.DescriptorConstructionInfo.<init>(DescriptorConstructionInfo.java:67)
	at org.jboss.shrinkwrap.descriptor.api.DescriptorInstantiator.getDescriptorConstructionInfoForUserView(DescriptorInstantiator.java:248)
	at org.jboss.shrinkwrap.descriptor.api.DescriptorInstantiator.createFromUserView(DescriptorInstantiator.java:88)
	at org.jboss.shrinkwrap.descriptor.api.Descriptors.create(Descriptors.java:69)
	at org.jboss.shrinkwrap.descriptor.api.Descriptors.create(Descriptors.java:46)
	at org.wildfly.swarm.undertow.JBossWebAsset.lambda$new$0(JBossWebAsset.java:36)
	at org.wildfly.swarm.container.util.ClassLoading.withTCCL(ClassLoading.java:26)
	at org.wildfly.swarm.undertow.JBossWebAsset.<init>(JBossWebAsset.java:35)
	at org.wildfly.swarm.undertow.JBossWebContainer.findJbossWebAsset(JBossWebContainer.java:56)
	at org.wildfly.swarm.undertow.JBossWebContainer.setDefaultContextRoot(JBossWebContainer.java:29)
	at org.wildfly.swarm.jaxrs.JAXRSArchiveImpl.<init>(JAXRSArchiveImpl.java:94)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.jboss.shrinkwrap.descriptor.spi.node.NodeDescriptorImplBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```

**Comment by emag** [comment]
@dzwicker Thank you for your checking. hmm, it's strange. It works on my environment...
![screenshot from 2015-11-10 17-24-50](https://cloud.githubusercontent.com/assets/1188893/11057641/249b6c4e-87d0-11e5-9a33-f5730fcd155a.png)

I assume it's not gradle problem. Does this reproduce in other example project using maven such like jaxrs-shirinkwrap?

**Comment by dzwicker** [comment]
jaxrs-shirinkwrap works perfectly

**Comment by dzwicker** [comment]
I have found the problems. But don't understand why... The cause is not using the default wrapper in idea settings. Is the gradle wrapper checkin a custom one? If i use the second option idea misses some dependencies.

![screen shot 2015-11-10 at 11 34 10](https://cloud.githubusercontent.com/assets/500483/11060234/26d22b8c-879f-11e5-9f50-cf6290844544.png)

**Comment by emag** [comment]
Oh, really? I'm checking `Use local gradle distribution`. FWIW, after I changed from gvm to sdkman, some 
![screenshot from 2015-11-10 19-42-25](https://cloud.githubusercontent.com/assets/1188893/11060441/a18e5546-87e3-11e5-864e-20bcf47a9053.png)
problems occurred(can't import gradle project or something).

So, your problem has fixed by using checking `Use default gradle wrapper`?

**Comment by dzwicker** [comment]
Yes
